import io, wave
from piper import PiperVoice

voice = PiperVoice.load("./piper_models/tr_TR-dfki-medium.onnx")

buf = io.BytesIO()
with wave.open(buf, 'wb') as wf:
    wf.setnchannels(1)
    wf.setsampwidth(2)
    wf.setframerate(22050)
    voice.synthesize("Merhaba, nasılsın?", wf)

print("Generated bytes length:", len(buf.getvalue()))
